### ISSUE TITLE
New loading function

### ISSUE THREAD

**Issue by jbirkesteen** [FireGutter/geneference#32]
## Aim
We want to create a loading function that can merge as many results as the user wishes.

## Procedure
1. Ask the user to specify a path to a directory containing results of analysing a simulation
2. Check which files exist in this folder
3. Check which of these files contain results (do some checks on columns)
4. Either:
   - Prompt the user to specify which of the files the user want to merge
   - Or take all usable files from directory
5. Either:
   - Prompt the user for each file to specify the suffix
   - Or have defaults for names based on file extension of analysis
6. Do the merges

**Comment by Javert-ctrl** [comment]
I have made the function so that input is a path to the folder with the analysis files. The function also takes "vars" as input - these are the variables used in the analysis-phase. The user then have multiple choices when loading - if they want to load one file, all files or a range of files. The function automatically assign meaning-ful names to coulmns - using the title of the different documents.
Lastly the function return a merged dataset.
